backend:
  name: github
  repo: josiahkatz/josiahkatz.github.io
  branch: master
  auth_endpoint: /auth

publish_mode: simple

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "notes"
    label: "Notes"
    folder: "content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Text", name: "text", widget: "string" }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
